Code review for project
evgenabramov/MIPT-Python-ToDoList pull request #1
Opened 2019-04-24 20:40 UTC by evgenabramov

2019-05-12 13:46 UTC, WokinShopash requested changes

2019-05-12 13:46 UTC, WokinShopash commented on server/database.py
> +params = dict(dbname='default', user="evgenabramov", password="12345678", host="localhost")
Вот эти параметры должны быть кастомизируемы, т.к. на моей машине такого пользователя нет.

2019-05-12 13:46 UTC, WokinShopash commented on client/parser.py
> +def build_add_task_parser():
`> ./client.py add_task --name "Make Review"`
Все отработало со стороны клиента нормально, никаких ошибок
А по факту на сервере ошибка.
```
  File "/home/wokinshopash/Python MIPT 2019/review2/users/evgenabramov/server/database.py", line 26, in add_task
    (task.name, datetime.datetime.strftime(task.due_date, '%Y-%m-%d'), task.description))
TypeError: descriptor 'strftime' requires a 'datetime.date' object but received a 'NoneType'
::ffff:127.0.0.1 - - [12/May/2019 16:22:22] "GET /show_tasks HTTP/1.1" 200 -
```
1. Всегда нужно ловить потенциальные исключения на сервере и отдавать их на клиент
2. Саму ошибку тоже надо полечить

2019-05-12 13:46 UTC, WokinShopash commented on client/parser.py
> +def build_mark_completed_parser():
`./client.py mark_completed --name "test"`\
Такой таски я не создавал, при этом программа отработала без ошибок, а наверное, должна была сказать, что я что-то не так делаю.

Я так думаю, подобные проблемы у тебя еще где-то будут

2019-05-12 13:46 UTC, WokinShopash commented on client/client.py
> +    requests.post(url, json=json.dumps(task))
Фишка аргумента json как раз в том, чтобы самому не приводить к JSON. Он сам под капотом делает dumps

2019-05-12 13:46 UTC, WokinShopash commented on client/lib.py
> +import datetime
Этот файлик надо не копировать, а положить снаружи.
Импортить можно вот так: https://docs.python.org/3/reference/import.html#package-relative-imports

2019-05-12 13:46 UTC, WokinShopash commented on client/lib.py
> +    def __repr__(self):
Я бы сказал, что это все-таки `__str__`, потому что `__repr__` более технический, и скорее должен соответствовать шаблону `<classname>(<init args>)`

2019-05-16 14:25 UTC, evgenabramov commented on client/lib.py
> +import datetime
Спасибо! Я долго пытался найти, как это сделать...

2019-06-19 14:28 UTC, merged